# Generated by Django 4.2 on 2023-07-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LetterCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("letter_url", models.CharField(max_length=200)),
                ("letter_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("user_pw", models.CharField(max_length=50)),
                ("user_email", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(verbose_name="data published")),
                (
                    "lettercase_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letters.lettercase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_id", models.CharField(max_length=50)),
                ("visitor_pw", models.CharField(max_length=50)),
                ("letter_text", models.CharField(max_length=255)),
                (
                    "lettercase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letters.lettercase",
                    ),
                ),
            ],
        ),
    ]
