# Generated by Django 4.2 on 2023-08-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lettercase_url",
            field=models.CharField(default="", max_length=200, null=True),
        ),
    ]
