# Generated by Django 4.2 on 2023-08-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="letter", old_name="letter_title", new_name="title",
        ),
    ]
