# Generated by Django 4.2 on 2023-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=50),
        ),
    ]
