# Generated by Django 4.2 on 2023-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0002_alter_user_lettercase_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="password", field=models.CharField(max_length=100),
        ),
    ]
