# Generated by Django 4.2 on 2023-08-10 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0003_alter_user_lettercase_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="lettercase", name="user_id",),
        migrations.AddField(
            model_name="lettercase",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lettercase",
            name="letter_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="lettercase_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
