# Generated by Django 4.2 on 2023-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0004_alter_user_lettercase_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lettercase_url",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
