# Generated by Django 4.2.13 on 2025-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0005_alter_user_lettercase_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='visitor_pw',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
