# Generated by Django 4.2.13 on 2025-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_remove_letter_visitor_pw_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letter',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
